pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
  - name: close stale pull request
    conditions:
      - base=main
      - -closed
      - updated-at<7 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.
  - name: Autoreviewer
    conditions:
      - -closed
      - -draft
    actions:
      request_reviews:
        users:
          - thewilloftheshadow
